export const waterQuantities = {
  normalWater19: 1,
  normalWater13: 2,
  normalWater11: 2,
  mineralWater19: 1,
  mineralWater13: 2,
  mineralWater11: 2,
};

export const catalogWaterData = [
  {
    name: 'Очищена',
    description: 'Здорова Вода',
    price: 130,
    priceFrom2To5: 110,
    priceFrom6To9: 100,
    priceFrom10: 95,
    image: '/bottle19L.png',
    volume: 19,
    width: 102,
    height: 144,
    type: 'normalWater',
  },
  {
    name: 'Мінералізована',
    description: 'Здорова Вода',
    price: 140,
    priceFrom2To5: 120,
    priceFrom6To9: 110,
    priceFrom10: 100,
    image: '/bottle19L.png',
    volume: 19,
    width: 102,
    height: 144,
    type: 'mineralWater',
  },
  {
    name: 'Очищена',
    description: 'Здорова Вода',
    price: 75,
    image: '/bottle13L.png',
    volume: 13,
    width: 168,
    height: 120,
    type: 'normalWater',
  },
  {
    name: 'Мінералізована',
    description: 'Здорова Вода',
    price: 80,
    image: '/bottle13L.png',
    volume: 13,
    width: 168,
    height: 120,
    type: 'mineralWater',
  },
  {
    name: 'Очищена',
    description: 'Здорова Вода',
    price: 70,
    image: '/bottle11L.png',
    volume: 11,
    width: 140,
    height: 100,
    type: 'normalWater',
  },
  {
    name: 'Мінералізована',
    description: 'Здорова Вода',
    price: 75,
    image: '/bottle11L.png',
    volume: 11,
    width: 140,
    height: 100,
    type: 'mineralWater',
  },
];
