export const pumpsData = [
  {
    name: "Blue Rain Extra",
    description: "Помпа механічна",
    price: 160,
    image: "/blueRain.png",
    quantity: 1,
  },
  {
    name: "VIO P8",
    description: "Помпа механічна з краником",
    price: 220,
    image: "/VioP8.png",
    quantity: 1,
  },
  {
    name: "Lilu Standart Plus",
    description: "Помпа механічна з краником",
    price: 240,
    image: "/LiluStandart.png",
    quantity: 1,
  },
  {
    name: "VIO E9 white",
    description: "Помпа електрична",
    price: 340,
    image: "/VioE9.png",
    quantity: 1,
  },
  {
    name: "HUANJI",
    description: "Помпа для води електрична",
    price: 620,
    image: "/Huanji.png",
    quantity: 1,
  },
  {
    name: "Aqua Pump Elite чорна",
    description: "Помпа для води електрична",
    price: 650,
    image: "/AquaPumpElitBlack.png",
    quantity: 1,
  },
  {
    name: "Aqua Pump Elite біла",
    description: "Помпа для води електрична",
    price: 650,
    image: "/AquaPumpElitWhite.png",
    quantity: 1,
  },
  {
    name: "Aqua Pump Elite жовта",
    description: "Помпа для води електрична",
    price: 690,
    image: "/AquaPumpElitYellow.png",
    quantity: 1,
  },
  {
    name: "SaengQ біла",
    description: "Помпа для води електрична",
    price: 950,
    image: "/SaenqQWhite.png",
    quantity: 1,
  },
  {
    name: "SaengQ чорна",
    description: "Помпа для води електрична",
    price: 950,
    image: "/SaenqQBlack.png",
    quantity: 1,
  },
  {
    name: "Xiaomi Xiaolang TDS",
    description: "Помпа для води електрична",
    price: 990,
    image: "/XiaomiTDS.png",
    quantity: 1,
  },
];
