export const pumpsData = [
  {
    id: "pump-blue-rain-extra",
    name: "Blue Rain Extra",
    description: "Помпа механічна",
    price: 240,
    image: "/blueRain.png",
    quantity: 1,
    width: 144,
    height: 144,
  },
  {
    id: "pump-lilu-econom-plus",
    name: "Lilu Econom Plus",
    description: "Помпа механічна з краником",
    price: 300,
    image: "/VioP8.png",
    quantity: 1,
    width: 171.38,
    height: 144,
  },
  {
    id: "pump-lilu-standart-plus",
    name: "Lilu Standart Plus",
    description: "Помпа механічна з краником",
    price: 310,
    image: "/LiluStandart.png",
    quantity: 1,
    width: 144,
    height: 144,
  },
  {
    id: "pump-vio-e9-white",
    name: "VIO E9 white",
    description: "Помпа електрична",
    price: 400,
    image: "/VioE9.png",
    quantity: 1,
    width: 280.79,
    height: 144,
  },
  {
    id: "pump-aqua-elite-black",
    name: "Aqua Pump Elite чорна",
    description: "Помпа для води електрична",
    price: 690,
    image: "/AquaPumpElitBlack.png",
    quantity: 1,
    width: 158.9,
    height: 144,
  },
  {
    id: "pump-aqua-elite-white",
    name: "Aqua Pump Elite біла",
    description: "Помпа для води електрична",
    price: 690,
    image: "/AquaPumpElitWhite.png",
    quantity: 1,
    width: 167.67,
    height: 144,
  },
  {
    id: "pump-aqua-elite-yellow",
    name: "Aqua Pump Elite жовта",
    description: "Помпа для води електрична",
    price: 690,
    image: "/AquaPumpElitYellow.png",
    quantity: 1,
    width: 203.61,
    height: 144,
  },
  {
    id: "pump-saengq-white",
    name: "SaengQ біла",
    description: "Помпа для води електрична",
    price: 950,
    image: "/SaenqQWhite.png",
    quantity: 1,
    width: 173.01,
    height: 144,
  },
  {
    id: "pump-saengq-black",
    name: "SaengQ чорна",
    description: "Помпа для води електрична",
    price: 950,
    image: "/SaenqQBlack.png",
    quantity: 1,
    width: 178.39,
    height: 144,
  },
  {
    id: "pump-xiaomi-xiaolang",
    name: "Xiaomi Xiaolang",
    description: "Помпа для води електрична",
    price: 1090,
    image: "/XiaomiTDS.png",
    quantity: 1,
    width: 178.69,
    height: 144,
  },
];
