export const pumpsData = [
  {
    name: "Blue Rain Extra",
    description: "Помпа механічна",
    price: 195,
    image: "/blueRain.png",
    quantity: 1,
    width: 144,
    height: 144,
  },
  {
    name: "VIO P8",
    description: "Помпа механічна з краником",
    price: 260,
    image: "/VioP8.png",
    quantity: 1,
    width: 171.38,
    height: 144,
  },
  {
    name: "Lilu Standart Plus",
    description: "Помпа механічна з краником",
    price: 270,
    image: "/LiluStandart.png",
    quantity: 1,
    width: 144,
    height: 144,
  },
  {
    name: "VIO E9 white",
    description: "Помпа електрична",
    price: 360,
    image: "/VioE9.png",
    quantity: 1,
    width: 280.79,
    height: 144,
  },
  /*{
    name: "HUANJI",
    description: "Помпа для води електрична",
    price: 620,
    image: "/Huanji.png",
    quantity: 1,
    width: 170.67,
    height: 144,
  },*/
  {
    name: "Aqua Pump Elite чорна",
    description: "Помпа для води електрична",
    price: 690,
    image: "/AquaPumpElitBlack.png",
    quantity: 1,
    width: 158.9,
    height: 144,
  },
  {
    name: "Aqua Pump Elite біла",
    description: "Помпа для води електрична",
    price: 690,
    image: "/AquaPumpElitWhite.png",
    quantity: 1,
    width: 167.67,
    height: 144,
  },
  {
    name: "Aqua Pump Elite жовта",
    description: "Помпа для води електрична",
    price: 690,
    image: "/AquaPumpElitYellow.png",
    quantity: 1,
    width: 203.61,
    height: 144,
  },
  {
    name: "SaengQ біла",
    description: "Помпа для води електрична",
    price: 950,
    image: "/SaenqQWhite.png",
    quantity: 1,
    width: 173.01,
    height: 144,
  },
  {
    name: "SaengQ чорна",
    description: "Помпа для води електрична",
    price: 950,
    image: "/SaenqQBlack.png",
    quantity: 1,
    width: 178.39,
    height: 144,
  },
  {
    name: "Xiaomi Xiaolang TDS",
    description: "Помпа для води електрична",
    price: 990,
    image: "/XiaomiTDS.png",
    quantity: 1,
    width: 178.69,
    height: 144,
  },
];
