export const BottlesAndAccessoriesData = [
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 11,
    quantity: 1,
    price: 300,
    image: "/Greif11L.png",
    width: 110,
    height: 110,
  },
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 13,
    quantity: 1,
    price: 320,
    image: "/Greif13L.png",
    width: 168,
    height: 140,
  },
  {
    name: "Бутель Yugin",
    description: "Полікарбонатний з ручкою",
    volume: 18.9,
    quantity: 1,
    price: 350,
    image: "/Yugin19L.png",
    width: 108,
    height: 144,
  },
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 18.9,
    quantity: 1,
    price: 390,
    image: "/Greif19L.png",
    width: 137.04,
    height: 144,
  },

  {
    name: "Ручка для бутля",
    description: "В асортименті",
    volume: 11,
    quantity: 1,
    price: 70.0,
    image: "/Holder11L.png",
    width: 120,
    height: 120,
  },
  {
    name: "Ручка для бутля",
    description: "В асортименті",
    volume: 13,
    quantity: 1,
    price: 80.0,
    image: "/Holder13L.png",
    width: 271.48,
    height: 144,
  },
  {
    name: "Ручка для бутля",
    description: "В асортименті",
    volume: 18.9,
    quantity: 1,
    price: 80.0,
    image: "/Holder19L.png",
    width: 192,
    height: 120,
  },
  {
    name: "Пробка для бутля",
    description: "Багаторазова",
    volume: 11,
    quantity: 1,
    price: 60,
    image: "/Cork.png",
    width: 120,
    height: 120,
  },
  {
    name: "Пробка для бутля",
    description: "Багаторазова",
    volume: 13,
    quantity: 1,
    price: 60,
    image: "/Cork.png",
    width: 120,
    height: 120,
  },
  {
    name: "Пробка для бутля",
    description: "Багаторазова",
    volume: 18.9,
    quantity: 1,
    price: 60,
    image: "/Cork.png",
    width: 120,
    height: 120,
  },
  {
    name: "Кран-клапан",
    description: "Для бутлів",
    volume: 11,
    quantity: 1,
    price: 95,
    image: "/Klapan11L.png",
    width: 144,
    height: 144,
  },
  {
    name: "Кран-клапан",
    description: "Для бутлів",
    volume: 13,
    quantity: 1,
    price: 95,
    image: "/Klapan13L.png",
    width: 144,
    height: 144,
  },
  {
    name: "Кран-клапан",
    description: "Для бутлів",
    volume: 18.9,
    quantity: 1,
    price: 95,
    image: "/Klapan11L.png",
    width: 144,
    height: 144,
  },
  {
    name: "Лійка для бутля",
    description: "Багаторазова",
    volume: 11,
    quantity: 1,
    price: 80,
    image: "/wateringPot.png",
    width: 230.4,
    height: 144,
  },
  {
    name: "Лійка для бутля",
    description: "Багаторазова",
    volume: 13,
    quantity: 1,
    price: 80,
    image: "/wateringPot.png",
    width: 230.4,
    height: 144,
  },
  {
    name: "Лійка для бутля",
    description: "Багаторазова",
    volume: 18.9,
    quantity: 1,
    price: 80,
    image: "/wateringPot.png",
    width: 230.4,
    height: 144,
  },
];
