export const bottlesAndAccessoriesData = [
  {
    id: "bottle-yugin-18-9",
    name: "Бутель Yugin",
    description: "Полікарбонатний без ручки",
    volume: 18.9,
    quantity: 1,
    price: 440,
    image: "/Yugin19L.png",
    width: 108,
    height: 144,
  },
  {
    id: "bottle-greif-18-9",
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 18.9,
    quantity: 1,
    price: 480,
    image: "/Greif19L.png",
    width: 137.04,
    height: 144,
  },
  {
    id: "bottle-holder",
    name: "Ручка для бутля",
    description: "В асортименті",
    volume: 18.9,
    quantity: 1,
    price: 110.0,
    image: "/Holder19L.png",
    width: 192,
    height: 120,
  },
  {
    id: "bottle-cork-reusable",
    name: "Пробка для бутля",
    description: "Багаторазова",
    volume: 18.9,
    quantity: 1,
    price: 80,
    image: "/Cork.png",
    width: 120,
    height: 120,
  },
  {
    id: "bottle-tap-valve",
    name: "Кран-клапан",
    description: "Для бутлів",
    volume: 18.9,
    quantity: 1,
    price: 120,
    image: "/Klapan11L.png",
    width: 144,
    height: 144,
  },
  {
    id: "bottle-funnel",
    name: "Лійка для бутля",
    description: "Багаторазова",
    volume: 18.9,
    quantity: 1,
    price: 80,
    image: "/wateringPot.png",
    width: 230.4,
    height: 144,
  },
];
