export const BottlesAndAccessoriesData = [
  {
    name: "Бутель Yugin",
    description: "Полікарбонатний без ручки",
    volume: 18.9,
    quantity: 1,
    price: 410,
    image: "/Yugin19L.png",
    width: 108,
    height: 144,
  },
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 18.9,
    quantity: 1,
    price: 460,
    image: "/Greif19L.png",
    width: 137.04,
    height: 144,
  },
  {
    name: "Ручка для бутля",
    description: "В асортименті",
    volume: 18.9,
    quantity: 1,
    price: 110.0,
    image: "/Holder19L.png",
    width: 192,
    height: 120,
  },
  {
    name: "Пробка для бутля",
    description: "Багаторазова",
    volume: 18.9,
    quantity: 1,
    price: 80,
    image: "/Cork.png",
    width: 120,
    height: 120,
  },
  {
    name: "Кран-клапан",
    description: "Для бутлів",
    volume: 18.9,
    quantity: 1,
    price: 120,
    image: "/Klapan11L.png",
    width: 144,
    height: 144,
  },
  {
    name: "Лійка для бутля",
    description: "Багаторазова",
    volume: 18.9,
    quantity: 1,
    price: 80,
    image: "/wateringPot.png",
    width: 230.4,
    height: 144,
  },
];
