export const BottlesAndAccessoriesData = [
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 11,
    quantity: 1,
    price: 300,
    image: "/Greif11L.png",
  },
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 13,
    quantity: 1,
    price: 320,
    image: "/Greif13L.png",
  },
  {
    name: "Бутель Yugin",
    description: "Полікарбонатний з ручкою",
    volume: 18.9,
    quantity: 1,
    price: 350,
    image: "/Yugin19L.png",
  },
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 18.9,
    quantity: 1,
    price: 390,
    image: "/Greif19L.png",
  },
  {
    name: "Бутель Greif",
    description: "Полікарбонатний з ручкою",
    volume: 18,
    quantity: 1,
    price: 390,
    image: "/Greif11L.png",
  },
  {
    name: "Ручка для бутля",
    description: "11л",
    volume: 11,
    quantity: 1,
    price: 70.0,
    image: "/Holder11L.png",
  },
  {
    name: "Ручка для бутля",
    description: "13л",
    volume: 13,
    quantity: 1,
    price: 80.0,
    image: "/Holder13L.png",
  },
  {
    name: "Ручка для бутля",
    description: "18.9л",
    volume: 18.9,
    quantity: 1,
    price: 80.0,
    image: "/Holder19L.png",
  },
  {
    name: "Пробка для бутля",
    description: "11л",
    volume: 11,
    quantity: 1,
    price: 0,
    image: "/Cork.png",
  },
  {
    name: "Кран-клапан",
    description: "11л",
    volume: 11,
    quantity: 1,
    price: 0,
    image: "/Klapan11L.png",
  },
  {
    name: "Лійка для бутля",
    description: "11л",
    volume: 11,
    quantity: 1,
    price: 0,
    image: "/wateringPot.png",
  },
];
