export const bottleStandData = [
  {
    name: "ViO WS-1 бук",
    description: "Підставка дерев'яна під 1 бутель",
    price: 615,
    image: "/ViO_WS-1.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WS-1 венге",
    description: "Підставка дерев'яна під 1 бутель",
    price: 690,
    image: "/ViO_WS-1_venge.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WS-2 бук",
    description: "Підставка дерев'яна під 2 бутлi",
    price: 760,
    image: "/ViO_WS-2_buk.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WS-2 венге",
    description: "Підставка дерев'яна під 2 бутлi",
    price: 820,
    image: "/ViO_WS-2_venge.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WS-2 зебрано",
    description: "Підставка дерев'яна під 2 бутлi",
    price: 780,
    image: "/ViO_WS-2_zebrano.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WS-3 бук",
    description: "Підставка дерев'яна під 3 бутлi",
    price: 970,
    image: "/ViO_WS-3_buk.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WS-3 венге",
    description: "Підставка дерев'яна під 3 бутлi",
    price: 990,
    image: "/ViO_WS-3_venge.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WS-3 зебрано",
    description: "Підставка під диспенсер низька",
    price: 990,
    image: "/ViO_WS-3_zebrano.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WSD-1 бук",
    description: "Підставка під диспенсер низька",
    price: 300,
    image: "/ViO_WSD-1_buk.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO WSD-1 венге",
    description: "Підставка під диспенсер низька",
    price: 320,
    image: "/ViO_WSD-1_venge.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO MS-1 металева чорна",
    description: "Підставка під 1 бутель настільна",
    price: 350,
    image: "/ViO_MS-1_metBlack.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO MS-2 металева біла",
    description: "Підставка під 1 бутель настільна",
    price: 350,
    image: "/ViO_MS-2_metWhite.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "VIO MS-3 похила металева",
    description: "Підставка під 1 бутель настільна",
    price: 420,
    image: "/VIO_MS-3_met.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO AХ-1 металева збірна",
    description: "Підставка під 2 бутлі напольна",
    price: 980,
    image: "/ViO_AХ-1-metConst.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
  {
    name: "ViO AD-2 металева збірна",
    description: "Підставка під 3 бутлі напольна",
    price: 1480,
    image: "/ViO_AD-2_metConst.png",
    quantity: 1,
    width: 100.27,
    height: 144,
  },
  {
    name: "ViO AD-3 металева збірна",
    description: "Підставка під 4 бутлі напольна",
    price: 1890,
    image: "/ViO_AD-3_metConst.png",
    quantity: 1,
    width: 72,
    height: 144,
  },
  {
    name: "ViO AD-11 металева збірна",
    description: "Підставка під 6 бутлів напольна",
    price: 1980,
    image: "/ViO_AD-11_metConst.png",
    quantity: 1,
    width: 230.4,
    height: 144,
  },
];
