export const bottleStandData = [
  {
    name: "ViO WS-1 бук",
    description: "Підставка дерев'яна під 1 бутель",
    price: 615,
    image: "/ViO_WS-1.png",
    quantity: 1,
    width: 230,
    height: 144,
  },
  {
    name: "ViO WS-1 венге",
    description: "Підставка дерев'яна під 1 бутель",
    price: 690,
    image: "/ViO_WS-1_venge.png",
    quantity: 1,
    width: 230,
    height: 144,
  },
  {
    name: "ViO WS-2 бук",
    description: "Підставка дерев'яна під 2 бутлi",
    price: 760,
    image: "/ViO_WS-2_buk.png",
    quantity: 1,
    width: 230,
    height: 144,
  },
  {
    name: "ViO WS-2 венге",
    description: "Підставка дерев'яна під 2 бутлi",
    price: 820,
    image: "/ViO_WS-2_venge.png",
    quantity: 1,
    width: 230,
    height: 144,
  },
  {
    name: "ViO WS-2 зебрано",
    description: "Підставка дерев'яна під 2 бутлi",
    price: 780,
    image: "/ViO_WS-2_zebrano.png",
    quantity: 1,
    width: 230,
    height: 144,
  },
  {
    name: "ViO WS-3 бук",
    description: "Підставка дерев'яна під 3 бутлi",
    price: 970,
    image: "/ViO_WS-3_buk.png",
    quantity: 1,
    width: 230,
    height: 144,
  },
  // Добавьте остальные элементы с аналогичной структурой...
];
