export const CoolersData = [
  {
    name: "ViO Х39-TN White",
    description: "Настільний кулер для води нагрів без охолодження",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 2990,
    image: "/ViO_Х39-TN_White.png",
  },
  {
    name: "ViO Х903-TN Black",
    description: "Настільний кулер для води нагрів без охолодження",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 3550,
    image: "/ViO_Х903-TN_Black.png",
  },
  {
    name: "ViO Х903-TN White",
    description: "Настільний кулер для води нагрів без охолодження",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 3500,
    image: "/ViO_Х903-TN_White.png",
  },
  {
    name: "ViO Х903- TЕ Black",
    description: "Настільний кулер для води з електронним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 4080,
    image: "/ViO_Х903-TЕ_Black.png",
  },
  {
    name: "ViO Х903- TЕ White",
    description: "Настільний кулер для води з електронним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 3980,
    image: "/ViO_Х903-TЕ_White.png",
  },
  {
    name: "ViO Х12-FEC White",
    description: "Підлоговий кулер для води з електронним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 7690,
    image: "/ViO_Х12-FEC_White.png",
  },
  {
    name: "ViO Х12-FEC Black",
    description: "Підлоговий кулер для води з електронним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 7850,
    image: "/ViO_Х12-FEC_Black.png",
  },
  {
    name: "ViO Х172-FEC з шафкою",
    description: "Підлоговий кулер для води з електронним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 7850,
    image: "/ViO_Х172-FEC.png",
  },
  {
    name: "VIO X903-FEC White",
    description: "Підлоговий кулер для води з електронним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 5720,
    image: "/VIO_X903-FEC_White.png",
  },
  {
    name: "ViO Х172-FСC з шафкою",
    description: "Підлоговий кулер для води з компресорним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 7925,
    image: "/ViO_Х172-FEC.png",
  },
  {
    name: "Х172-FСF + холодильник",
    description: "Підлоговий кулер для води з компресорним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 8035,
    image: "/Х172-FСF.png",
  },
  {
    name: "ViO Х217-FCC з шафкою",
    description: "Підлоговий кулер для води з компресорним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 7300,
    image: "/ViO_Х217-FCC.png",
  },
  {
    name: "Х217-FСF + холодильник",
    description: "Підлоговий кулер для води з компресорним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 8250,
    image: "/ViO_Х217-FCC.png",
  },
  {
    name: "VIO X903-FCC з шафкою",
    description: "Підлоговий кулер для води з компресорним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 7550,
    image: "/VIO_X903_FCC.png",
  },
  {
    name: "VIO X62-FCC з шафкою",
    description: "Підлоговий кулер для води  з компресорним охолодженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 9100,
    image: "/VIO_X62-FCC.png",
  },
  {
    name: "X83-FCC ROSE з шафкою",
    description: "Підлоговий кулер для води з компресорним охолодженням",
    width: 156.1,
    height: 144,
    quantity: 1,
    price: 6850,
    image: "/X83-FCC_ROSE.png",
  },
  {
    name: "X601-FCB black компрес",
    description: "Підлоговий кулер для води з нижнім завантаженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 11950,
    image: "/X601-FCB_black.png",
  },
  {
    name: "X601-FCB white компрес",
    description: "Підлоговий кулер для води з нижнім завантаженням",
    width: 230.4,
    height: 144,
    quantity: 1,
    price: 11950,
    image: "/X601-FCB_white.png",
  },
];
